name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  apk:
    name: Generate APK
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [32]
        target: [default]

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build debug APK
      run: bash ./gradlew assembleDebug --stacktrace
      
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: ./gradlew connectedCheck --stacktrace

    - name: action-slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: Github Action Test # default: 8398a7@action-slack
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.

    - name: Slack - Upload APK
      uses: MeilCli/slack-upload-file@v1.0.0
      with:
        slack_token: ${{ secrets.SLACK_TOKEN }}
        channels: ${{ secrets.SLACK_CHANNEL }}
        initial_comment: 'APK File Upload'
        file_type: 'apk'
        file_name: 'app-debug.apk'
        file_path: './app/build/outputs/apk/debug/app-debug.apk'
